apiVersion: v1
kind: Service
metadata:
  name: ezshop-accounts
spec:
  selector:
    app: ezshop-accounts
  type: ClusterIP # this is the default
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
# apiVersion: v1
# kind: Service
# metadata:
#   name: account-accounts
# spec:
#   selector:    
#     app: account-accounts
#   type: NodePort
#   ports:  
#   - name: http
#     port: 80
#     targetPort: 80
#     nodePort: 30000
#     protocol: TCP
